name: Deploy prod site on push

on: 
  push:
    branches: 
      - main
      
jobs:
  web-deploy:

    name: Deploy Angular App
    runs-on: ubuntu-latest

    env:
      SERVER: waws-prod-ln1-025.ftp.azurewebsites.windows.net

    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14 LTS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Install NPM Modules
      run: npm install

    - name: Build Project
      run: npm run build
      
    - name: Update Base Href Path
      run: sed -i 's|<base href="/">|<base href="/Videoflix/videoflix-front/">|' dist/index.html
      working-directory: ${{ github.workspace }}  
    
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        #remote-dir: /Videoflix
        server-dir: ./Videoflix/

